FROM eclipse-temurin:17-jdk-alpine as build

WORKDIR /app

# Install Maven
RUN apk add --no-cache maven

COPY . .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=build /app/target/challenge_java-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar", "--spring.profiles.active=prod"]
