FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY . .

RUN ./mvnw clean install -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "target/challenge_java-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=dev"]
